import json

# All questions including originals and new ones
all_questions = [
    {"stem": "When should a BWC be activated?", "choices": ["Only during arrests", "At the start of every police interaction", "Only when force is used", "When directed by supervisor"], "answer_idx": 1, "explanation": "BWC should be activated at the start of every police interaction. Officers must resume recording if stopped for any of the 10 exceptions.", "topic_name": "BWC", "source_ref": "BWC 2.0"},
    {"stem": "Which is NOT a BWC exception?", "choices": ["Attending to sexual offences", "Consuming official ease", "Routine traffic stops", "Within secured areas"], "answer_idx": 2, "explanation": "Routine traffic stops are NOT an exception. The 10 exceptions: sexual offences, secured areas, pumping petrol, hospital, consuming OE, personal communications, diplomat requests, MOP requests stop, anti-crime rounds with restrictions, non-crime in private places.", "topic_name": "BWC", "source_ref": "BWC 2.0"},
    {"stem": "Mary left bag to reserve seat. It was missing when she returned. Report type?", "choices": ["NP299 theft", "Station diary", "NP322 loss", "NP322 theft"], "answer_idx": 2, "explanation": "NP322 loss report. Without witnessing theft, classified as loss.", "topic_name": "Reports", "source_ref": "Ease Spring"},
    {"stem": "What does SALUTE reporting format stand for?", "choices": ["Standard Alert Level Update Time Equipment", "Size Activity Location Unit Time Equipment", "Security Assessment Level Unit Time Evaluation", "Situation Alert Location Update Time Environment"], "answer_idx": 1, "explanation": "SALUTE: Size (number), Activity (what), Location (where), Unit (reporting), Time (when), Equipment (weapons).", "topic_name": "SALUTE", "source_ref": "Ease Spring"},
    {"stem": "Ashley's brother watches radical videos and has bomb notes. Action?", "choices": ["Inform parents", "Call ISD hotline", "Ignore it", "Just advise brother"], "answer_idx": 1, "explanation": "Call ISD hotline. Radical content and bomb notes require professional intervention.", "topic_name": "Security Threats", "source_ref": "Ease Spring"},
    {"stem": "Off-duty officer witnesses armed parang attack. Action?", "choices": ["Film only", "Use improvised weapons to tackle", "Hide and observe", "Run away"], "answer_idx": 1, "explanation": "As officer, use improvised weapons and rally others to tackle attacker.", "topic_name": "Armed Attacks", "source_ref": "Ease Spring"},
    {"stem": "Officer checks FOCUS for report against his brother. Offence?", "choices": ["No offence", "Computer Misuse Act", "Only disciplinary", "Breach of trust"], "answer_idx": 1, "explanation": "Unauthorised access under Computer Misuse Act.", "topic_name": "Computer Misuse Act", "source_ref": "Ease Spring"},
    {"stem": "Can officer accept discount from complainant?", "choices": ["Yes if off-duty", "No, against PGO", "Yes with approval", "Yes, no issue"], "answer_idx": 1, "explanation": "Against PGO A10. Prevents conflicts of interest.", "topic_name": "PGO", "source_ref": "Ease Spring"},
    {"stem": "Officer treats friend differently. Shows lack of:", "choices": ["Courage", "Integrity", "Fairness", "Loyalty"], "answer_idx": 2, "explanation": "Lack of fairness. Must treat all equally.", "topic_name": "Police Values", "source_ref": "Ease Spring"},
    {"stem": "Seizing stolen items as exhibits:", "choices": ["Issue NP323 to suspect", "Diary only", "Issue NP323 to owner", "Verbal acknowledgment"], "answer_idx": 2, "explanation": "Issue NP323 to owner for documentation.", "topic_name": "Exhibits", "source_ref": "Ease Spring"},
    {"stem": "Subject felt compelled to follow officer, not told arrested. Is he arrested?", "choices": ["No, not restrained", "No, not told", "No, not handcuffed", "Yes, felt compelled"], "answer_idx": 3, "explanation": "Under CPC, arrested if felt compelled.", "topic_name": "Arrest", "source_ref": "Ease Spring"},
    {"stem": "Aircon noise complaint. Officer action?", "choices": ["Refer HDB", "Can't help", "Lodge report first", "Take statement first"], "answer_idx": 0, "explanation": "No criminal offence. Refer to HDB following NWD policy.", "topic_name": "NWD", "source_ref": "Ease Spring"},
    {"stem": "Ken posts abusive remarks about ex with her number. Strangers harass her. Offence?", "choices": ["Intentional Harassment S3 PHA", "Harassment S4 PHA", "No offence", "Stalking S7 PHA"], "answer_idx": 0, "explanation": "Intentional Harassment Section 3 Protection from Harassment Act.", "topic_name": "PHA", "source_ref": "Ease Spring"},
    {"stem": "Judy has friend's IC as loan security. Offence?", "choices": ["S13(1)(d) NRA", "No offence", "Fraudulent possession MOA", "Breach of trust"], "answer_idx": 0, "explanation": "Section 13(1)(d) National Registration Act. May arrest and seize IC.", "topic_name": "National Registration Act", "source_ref": "Ease Spring"},
    {"stem": "Jacky rubs leg against sleeping girl intentionally. Offence?", "choices": ["Indecent behaviour", "Outrages on decency", "Voyeurism", "Outrage of modesty"], "answer_idx": 3, "explanation": "Outrage of modesty S354 Penal Code.", "topic_name": "Sexual Offences", "source_ref": "Ease Spring"},
    {"stem": "Danny threatens Julie for handbag. She shouts, he flees. Offence?", "choices": ["Criminal intimidation", "Attempted robbery with hurt", "Extortion", "Attempted robbery"], "answer_idx": 3, "explanation": "Attempted robbery. Attempt itself is offence.", "topic_name": "Robbery", "source_ref": "Ease Spring"},
    {"stem": "Three rob store. One shoots cashier with unknown gun. Cashier dies. Who liable?", "choices": ["Only shooter", "All for robbery only", "All for murder in common intention", "All for conspiracy"], "answer_idx": 2, "explanation": "All liable for murder in furtherance of common intention.", "topic_name": "Common Intention", "source_ref": "Ease Spring"},
    {"stem": "Which offence is strict liability?", "choices": ["VCH", "Criminal Force", "Possession of offensive weapons", "Housebreaking"], "answer_idx": 2, "explanation": "Possession of offensive weapons is strict liability.", "topic_name": "Offensive Weapons", "source_ref": "Ease Spring"},
    {"stem": "Under Article 9 Constitution, arrested person must be:", "choices": ["All: informed of reasons, consult lawyer, before magistrate within 48 hours", "Only informed of reasons", "Only lawyer access", "Only before magistrate"], "answer_idx": 0, "explanation": "All apply under Article 9 constitutional rights.", "topic_name": "Constitutional Rights", "source_ref": "Ease Spring"},
    {"stem": "You ask a man for his particulars and he starts shouting vulgarities at you. What should you do first?", "choices": ["Arrest him immediately", "Warn him to stop using abusive words", "Walk away", "Record video as evidence"], "answer_idx": 1, "explanation": "Warn him first. Common trap: Choosing A. Arrest only if he continues after warning (POHA s6). One-liner: Warn before wrist.", "topic_name": "Dispute Management", "source_ref": "User Input"},
    {"stem": "Driver self-drove to hospital and got 2-day MC after accident.", "choices": ["Non-injury accident", "Property damage only", "Injury accident", "No report needed"], "answer_idx": 2, "explanation": "Injury accident. Trap: Thinking 'self-drive = non-injury.' Any MC = injury. One-liner: MC means NP168.", "topic_name": "Traffic", "source_ref": "User Input"},
    {"stem": "Photographing tiny object (<15 mm) at crime scene. What photos needed?", "choices": ["Two close-ups", "One wide shot only", "One close-up + one showing location", "Random angles"], "answer_idx": 2, "explanation": "Need one close-up and one showing location context. Trap: Two close-ups - no context. One-liner: Zoom and room.", "topic_name": "Crime Scene Photography", "source_ref": "User Input"},
    {"stem": "Subject kicks car door. What is your power?", "choices": ["Arrest immediately for Mischief", "Check particulars; arrest if he refuses", "Criminal intimidation", "Vandalism"], "answer_idx": 1, "explanation": "Mischief is non-arrestable; use CPC s65 to demand particulars. Trap: Thinking 'seen offence = arrest.' One-liner: See it, check it, don't clap it.", "topic_name": "Mischief", "source_ref": "User Input"},
    {"stem": "Subject claims diplomatic immunity. What should you do?", "choices": ["Ignore claim, arrest", "Verify via MFA through POCC", "Detain for screening", "Seize passport"], "answer_idx": 1, "explanation": "Must verify through MFA via POCC. Trap: Arresting without verification. One-liner: Call MFA before CFA.", "topic_name": "Diplomatic Immunity", "source_ref": "User Input"},
    {"stem": "You made wrong entry in report. What should you do?", "choices": ["Amend record", "Delete it", "Submit new report and VIDE link", "Leave it"], "answer_idx": 2, "explanation": "Submit new report and VIDE link. Trap: Editing original breaks audit trail. One-liner: Don't edit, add VIDE.", "topic_name": "Reports", "source_ref": "User Input"},
    {"stem": "Natural death (known illness). What should you do?", "choices": ["Activate DOR", "Ask family to get CCOD from doctor", "Send patrol", "Inform SCDF"], "answer_idx": 1, "explanation": "Ask family to get CCOD from doctor. Trap: Calling DOR for natural death. One-liner: Doctor first, not DOR first.", "topic_name": "Death Procedures", "source_ref": "User Input"},
    {"stem": "Which is NOT a GRF duty?", "choices": ["Manage incidents", "Proactive ops", "House visits", "Counter duties"], "answer_idx": 2, "explanation": "House visits = Community Policing. Trap: Assuming all choices fit. One-liner: Ops-Incident-Counter, no home visitor.", "topic_name": "GRF Duties", "source_ref": "User Input"},
    {"stem": "Handling dispute between two parties. What should you do?", "choices": ["Interview both together", "Stay neutral, separate parties", "Arrest both", "Warn both to leave"], "answer_idx": 1, "explanation": "Stay neutral and separate parties. Trap: Interviewing together escalates anger. One-liner: Split and stay fair.", "topic_name": "Dispute Management", "source_ref": "User Input"},
    {"stem": "Regarding chain of evidence, what must you do?", "choices": ["Let IO decide value", "Maintain continuous custody record", "Only IO handles evidence", "Lock exhibits in safe"], "answer_idx": 1, "explanation": "Maintain continuous custody record. Trap: Thinking only one officer can handle. One-liner: Track each hand for chain to stand.", "topic_name": "Evidence", "source_ref": "User Input"},
    {"stem": "Roadblock Stopper duties include:", "choices": ["Retain ID", "Record particulars and return ID", "Search vehicle", "Pass ID to Checker"], "answer_idx": 1, "explanation": "Record particulars and return ID. Trap: Keeping ID or handing to Checker. One-liner: Record, return, refer.", "topic_name": "Roadblock", "source_ref": "User Input"},
    {"stem": "Fake Customs Officer demands money. What offence?", "choices": ["Extortion", "Cheating", "Criminal intimidation", "Harassment"], "answer_idx": 1, "explanation": "Cheating s420 PC. Trap: Selecting Extortion (no fear of injury). One-liner: Lie for cash = Cheat, not Threat.", "topic_name": "Scams", "source_ref": "User Input"},
    {"stem": "NS man change of address - which agency?", "choices": ["ICA", "SPF HQ", "CMPB", "MOM"], "answer_idx": 2, "explanation": "CMPB handles NS matters. Trap: Assuming ICA handles all addresses. One-liner: Green IC = CMPB.", "topic_name": "Administrative", "source_ref": "User Input"},
    {"stem": "Crime-scene photo rules - which is WRONG?", "choices": ["Take objective photos", "Eye-level angle", "Replace moved items", "Show relevant objects"], "answer_idx": 2, "explanation": "Never re-stage scene. Trap: Thinking 'replace for clarity.' One-liner: Real, level, relevant.", "topic_name": "Crime Scene Photography", "source_ref": "User Input"},
    {"stem": "First step with complainant at counter?", "choices": ["Ask purpose of call", "Ask for ID", "Greet and introduce yourself", "Ask about suspect"], "answer_idx": 2, "explanation": "Greet and introduce yourself first. Trap: Skipping rapport-building. One-liner: Hello before why.", "topic_name": "Counter Duties", "source_ref": "User Input"},
    {"stem": "Alcohol test shows amber. What action?", "choices": ["Arrest", "No action", "Escort to hospital", "Retest immediately"], "answer_idx": 1, "explanation": "Amber = borderline, not fail. Trap: Arresting based on smell alone. One-liner: Amber okay, red no way.", "topic_name": "Traffic", "source_ref": "User Input"},
    {"stem": "12-year-old girl loitering at night alone. What action?", "choices": ["Arrest for loitering", "Bring to NPC", "Check particulars and advise to go home", "Detain for investigation"], "answer_idx": 2, "explanation": "Check particulars and advise. Trap: Detaining without offence. One-liner: No crime, just care.", "topic_name": "Juvenile", "source_ref": "User Input"},
    {"stem": "Who can activate Red Storm?", "choices": ["Ground commander only", "POCC only", "OC Ops, TL or Watch Commander", "Any patrol officer"], "answer_idx": 2, "explanation": "OC Ops, Team Leader or Watch Commander can activate. Trap: Thinking only HQ can do it. One-liner: TL or POCC can rock.", "topic_name": "Major Incidents", "source_ref": "User Input"},
    {"stem": "Role of Reporting Point in major incident?", "choices": ["Command arrest", "Debrief media", "Gather, brief and deploy officers", "Guard scene perimeter"], "answer_idx": 2, "explanation": "Gather, brief and deploy officers. Trap: Confusing with staging area for IO. One-liner: Meet, brief, assign.", "topic_name": "Major Incidents", "source_ref": "User Input"},
    {"stem": "UML graffiti (O$P$ #05-123) on unit door. What offence?", "choices": ["Mischief", "Vandalism", "UML harassment", "Public nuisance"], "answer_idx": 2, "explanation": "Valid unit + O$P$ = UML harassment. Trap: Marking as Mischief (no borrower identified). One-liner: O$P$ real door = UML for sure.", "topic_name": "UML", "source_ref": "User Input"}
]

# Write to file
with open('data/seeds/mcq.json', 'w') as f:
    json.dump(all_questions, f, indent=2)

print(f"Successfully wrote {len(all_questions)} questions to mcq.json")
